### PR TITLE
Fix issue: issue#31

### PR DESCRIPTION
**Pull request by Vvinathi**
I have fixed the issue by updating the favicon file paths in the HTML code. 
I hope it solves the issue?

### CODE REVIEW

**Comment by AsaiToshiya** [comment]
Usually correct fix, but those paths cannot referenced in https://asaitoshiya.github.io/brostr/src/ on GitHub Pages.

**Comment by Vvinathi** [comment]
Oh, Okay. But the paths you provided in your HTML code looks relative to GitHub directory.

**Comment by AsaiToshiya** [comment]
You also need to fix the following:

https://github.com/AsaiToshiya/brostr/blob/2e97e6606e26eb9b3a496b2e61485f94c149009e/src/index.html#L21-L22

**Comment by AsaiToshiya** [comment]
I think you can fix this by using `/brostr/images/apple-touch-icon.png` or `../images/apple-touch-icon.png`.

**Comment by AsaiToshiya** [comment]
@Vvinathi Thank you for fix. I merged it into main.

**Comment by Vvinathi** [comment]
Thanks a lot @AsaiToshiya.

**Pull request merged**
